version: '3'
services:
  lita: 
    build: . # use the local Dockerfile
    command: bash -c 'bundle exec lita'
    ports:
      - "3000:3000" # expose port 3000 as port 3000
    volumes:
      - .:/app # mount the current directory to /app
    environment:
      - RACK_ENV=production # Run the app in the 'development' environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:@db/cf-dx_development
      - LOG_LEVEL=debug
      - LITA_HTTP_PORT=80
      - REDIS_URL=redis://redis-lita:6379
      - SLACK_TOKEN=redacted
      - IMGFLIP_API_PASSWORD=redacted
      - IMGFLIP_API_USER=redacted
    depends_on:
      - redis-lita # define the required relationship
    tty: true
    stdin_open: true
  redis-lita:
    image: redis
    ports:
      - "6379"
