version: '3'
services:
  lita: 
  #build: . # use the local Dockerfile
    image: cfcontainersdp.azurecr.io/bookbot/lita:525af5
    command: bash -c 'bundle exec lita'
    ports:
      - "3000:3000" # expose port 3000 as port 3000
        #volumes:
        #- .:/app # mount the current directory to /app
    environment:
      - RACK_ENV=production # Run the app in the 'development' environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:@db/cf-dx_development
      - LOG_LEVEL=debug
      - LITA_HTTP_PORT=80
      - REDIS_URL=redis://redis-lita:6379
      - SLACK_TOKEN=xoxb-212869157184-qU51ZUEVGBVIl7ajJCSK1e7A
      - IMGFLIP_API_PASSWORD=memtech_elvis
      - IMGFLIP_API_USER=memtech_elvis
    depends_on:
      - redis-lita # define the required relationship
    tty: true
    stdin_open: true
  redis-lita:
    image: redis
    ports:
      - "6379"
